### ISSUE TITLE
Camera far clip planes feature request

### ISSUE THREAD

**Issue by jonnytracker** [ReachCloudDevelopers/MetaverseCloudEngine.Unity.SDK#34]
camera far clip planes default to 5000 during runtime. An option to customize it would be great for performance optimization on large environments.

**Comment by sollaholla** [comment]
Made some progress on this, still need to fix a few things though

**Comment by sollaholla** [comment]
Added a new component called `Override Cinemachine Clipping Planes` @jonnytracker
