### ISSUE TITLE
Network Create Game Object

### ISSUE THREAD

**Issue by PaesolVeera** [ReachCloudDevelopers/MetaverseCloudEngine.Unity.SDK#37]
Please have an easy way to create/instantiate network Game Object that is synchronized on Reach 2, either with PayerMaker or Component.

**Comment by sollaholla** [comment]
We already have a way to instantiate/create a networked object via component. This is called `Prefab Spawner`. The component will automatically spawn a prefab with a `Network Object` on it across the network.

However, PlayMaker actions have not yet been developed and will be.

**Comment by sollaholla** [comment]
Complete
